---
# Declare a service with a user-defined IP on a macvlan network, so that the container is visible from the outside
# It's an alternative to host network
services:
  test:
    image: busybox:latest
    command:
      - sh
      - -c
      - ip addr show eth0 && ip route && ping -c 1 ${GATEWAY:-10.66.0.1} && ping -c 1 1.1.1.1
    networks:
      mynet:
        ipv4_address: ${IP:-10.66.77.88}

networks:
  mynet:
    driver: macvlan
    driver_opts:
      parent: ${INTERFACE:-eth0}
    ipam:
      driver: default
      config:
        - subnet: ${SUBNET:-10.66.0.0/16}
          gateway: ${GATEWAY:-10.66.0.1}
