---
# Declare a service with on a ipvlan network, so that the container is visible from the outside
# It's an alternative to host network
services:
  test:
    image: busybox:latest
    command:
      - sh
      - -c
      - ip addr show eth0 && ip route && ping -c 1 ${GATEWAY:-10.66.0.1} && ping -c 1 1.1.1.1
    networks:
      - mynet

networks:
  mynet:
    driver: ipvlan
    driver_opts:
      parent: ${INTERFACE:-eth0}
    ipam:
      config:
        - subnet: ${SUBNET:-10.66.0.0/16}
          gateway: ${GATEWAY:-10.66.0.1}
          ip_range: ${IP_RANGE:-10.66.1.0/24}
